import type { Entity } from '../types';

// Seed data from the omnia world repo — 天星界武道世界
export const SEED_ENTITIES: Omit<Entity, 'owner_id' | 'created_at' | 'updated_at'>[] = [
  // ========== 境界体系 ==========
  {
    id: 'seed-realm-wudao',
    name: '武道境界',
    type: 'realm',
    icon: '🔮',
    summary: '天星界九洲武道修炼体系，共十三境。',
    description: '天星界修炼武道，共十三境：武仆 → 武者(1-9星) → 武师 → 大武师 → 武宗 → 大武宗 → 武王(下中上品) → 武君 → 武圣(1-9星) → 武帝 → 武尊 → 武皇 → 武神。\n\n武王封王可劈山断水；武圣成圣可增寿一万载；武帝称帝可建立不朽王朝（已是传说）；武尊登尊可破碎虚空；武神通神可飞升上界。\n\n九洲悠悠无数载，闻名江湖的多是武圣武君，武帝已是传说，武帝之上几乎无人知晓。',
    fields: [
      { key: 'order', label: '境界总览', value: '武仆→武者→武师→大武师→武宗→大武宗→武王→武君→武圣→武帝→武尊→武皇→武神' },
      { key: 'watershed1', label: '武王·封王', value: '劈山断水，战力质的飞跃' },
      { key: 'watershed2', label: '武圣·成圣', value: '增寿一万载，踏入圣境' },
      { key: 'watershed3', label: '武帝·称帝', value: '可建立不朽王朝，已是传说' },
      { key: 'watershed4', label: '武尊·登尊', value: '破碎虚空，跨越空间界限' },
      { key: 'watershed5', label: '武神·通神', value: '飞升上界，需渡无上天劫，失败则化道' },
    ],
    tags: ['境界', '武道', '天星界'],
    relationIds: ['seed-location-tianxingjie', 'seed-location-lianshenya', 'seed-character-qingcang'],
  },

  // ========== 地点 ==========
  {
    id: 'seed-location-tianxingjie',
    name: '天星界',
    type: 'location',
    icon: '🌍',
    summary: '天星界九洲，武道为尊的世界。',
    description: '不知何时，古书上就这样称呼脚下的大地为天星界。天星界共有九洲：极霞西洲、落华南洲、琼川东洲、荒溟北洲、逍遥云洲、耀神中洲、千盛瑶洲、天曌帝洲、琉璃苍洲。\n\n寰宇中央传说有四象神朝——朱雀、玄武、白虎、青龙——但谁也没见过有关神朝的任何记录。',
    fields: [
      { key: 'type', label: '类型', value: '主世界' },
      { key: 'alias', label: '别名', value: '寰宇' },
      { key: 'continents', label: '九洲', value: '极霞西洲、落华南洲、琼川东洲、荒溟北洲、逍遥云洲、耀神中洲、千盛瑶洲、天曌帝洲、琉璃苍洲' },
      { key: 'system', label: '修炼体系', value: '武道', linkedEntityId: 'seed-realm-wudao' },
      { key: 'mystery', label: '千古之谜', value: '寰宇中央四象神朝——无任何记录留存' },
    ],
    tags: ['世界', '天星界'],
    relationIds: ['seed-realm-wudao', 'seed-location-yunzhou'],
  },
  {
    id: 'seed-location-yunzhou',
    name: '逍遥云洲',
    type: 'location',
    icon: '🗺️',
    summary: '万族林立、炼丹圣地。三宗四门七世家，共14霸主势力。',
    description: '云洲有三宗、四门、七世家，共14个霸主势力，其间摩擦争斗不断。每家底蕴都是几千年起步。另有新兴势力血刀门，三年崛起已可比肩霸主。\n\n云洲能在九洲中排名前三，根本原因是炼神崖——一位武神在此渡劫失败化道，无尽道韵融入云洲大地，滋养了一洲万族。',
    fields: [
      { key: 'alias', label: '别称', value: '云洲' },
      { key: 'faction', label: '势力格局', value: '三宗四门七世家（14霸主）+ 新兴血刀门' },
      { key: 'top1', label: '最强霸主', value: '逍遥宗（主修剑道）' },
      { key: 'feature', label: '特色', value: '万族林立、炼丹圣地' },
      { key: 'history', label: '历史创伤', value: '气运枯竭——彩云大尊掠夺、帝洲入侵两次打击' },
      { key: 'landmark', label: '著名地标', value: '炼神崖（武神化道遗址）', linkedEntityId: 'seed-location-lianshenya' },
    ],
    tags: ['地点', '云洲'],
    relationIds: ['seed-location-tianxingjie', 'seed-location-lianshenya', 'seed-faction-tianyimen', 'seed-faction-xuedaomen', 'seed-faction-liujia'],
  },
  {
    id: 'seed-location-lianshenya',
    name: '炼神崖',
    type: 'location',
    icon: '⛰️',
    summary: '武神化道遗址，已被段山河炼化为弯刀。',
    description: '云洲东南部的传奇地标。曾有武神在此渡劫失败，被无上天劫炼化。神躯崩解，道韵回馈天地。武神化道后无尽道韵融入云洲大地，这也是云洲能在九洲中排名前三的根本原因。\n\n如今道韵已极其稀薄——武宗瞧不上，武师嫌弃，武者视若宝地。段山河在此获得三位存在赐予的传承，后战胜柳家三长老，将整座炼神崖炼化为一柄弯刀。从此炼神崖不复存在。',
    fields: [
      { key: 'type', label: '类型', value: '武神化道遗址' },
      { key: 'region', label: '所属洲域', value: '逍遥云洲东南部', linkedEntityId: 'seed-location-yunzhou' },
      { key: 'status', label: '现状', value: '已被段山河炼化为弯刀，不复存在' },
      { key: 'effect', label: '对云洲的影响', value: '武神化道滋养一洲万族，云洲排名前三的根本原因' },
      { key: 'mystery', label: '谜团', value: '段山河获得的传承来自三位庞大存在，非武神残留' },
    ],
    tags: ['地点', '云洲', '遗迹'],
    relationIds: ['seed-location-yunzhou', 'seed-character-duanshanhe', 'seed-realm-wudao'],
  },

  // ========== 势力 ==========
  {
    id: 'seed-faction-tianyimen',
    name: '天一门',
    type: 'faction',
    icon: '🏯',
    summary: '云洲四门之一，自诩正道。符修与器修闻名，外门五万余弟子。',
    description: '云洲四门之一，自诩正道宗门。数千年底蕴，外门五万余弟子，内门亦有数千。以符修与器修闻名，不拘一格吸纳百工杂学。门下设有裁决堂，对外剿灭邪道，对内执掌刑罚。\n\n管理架构：掌门 → 太上长老团 → 裁决堂 → 六院（符院、器院、丹院、传功院、外务院、内务院）→ 外门与内门。另有妖魔长老（武王境以上妖族）。',
    fields: [
      { key: 'origin', label: '底蕴', value: '数千年' },
      { key: 'scale', label: '规模', value: '外门五万余，内门数千' },
      { key: 'specialty', label: '功法特色', value: '符修与器修' },
      { key: 'structure', label: '管理架构', value: '掌门→太上长老团→裁决堂→六院→外门/内门' },
      { key: 'enemies', label: '敌对势力', value: '血刀门（已公开悬赏剿灭）', linkedEntityId: 'seed-faction-xuedaomen' },
      { key: 'darkside', label: '阴暗面', value: '门内有妖魔长老（武王境以上妖族），外门考核后小世界尘民被吞吃' },
    ],
    tags: ['正道', '云洲', '四门'],
    relationIds: ['seed-location-yunzhou', 'seed-faction-xuedaomen', 'seed-character-sudian', 'seed-character-suofeng', 'seed-character-xiaoluoli'],
  },
  {
    id: 'seed-faction-xuedaomen',
    name: '血刀门',
    type: 'faction',
    icon: '🗡️',
    summary: '三年崛起的新兴势力，可比肩云洲14霸主。实为域外异族所建。',
    description: '三年前崛起，如今实力已可比肩云洲14霸主势力之一。门主段山河（原名段刃），麾下9位武君效命。\n\n本质：段山河在炼神崖的梦境中被三位庞大存在赐予传承，受命在天星界建造宗门。巡天战皇将血刀门定性为"域外异族污染"。修炼法门为"炼人化刀"——血脉炼刀，击杀转化。九君的"拔升"来自三位存在的力量，非九洲武道传承。\n\n已被青沧至尊奉巡天战皇之命清剿，八君全灭。',
    fields: [
      { key: 'leader', label: '门主', value: '段山河', linkedEntityId: 'seed-character-duanshanhe' },
      { key: 'core', label: '核心战力', value: '9位武君（九君）' },
      { key: 'origin', label: '起源', value: '段山河在炼神崖获三位存在传承后创建', linkedEntityId: 'seed-location-lianshenya' },
      { key: 'method', label: '修炼法门', value: '炼人化刀——血脉炼刀，击杀转化' },
      { key: 'nature', label: '本质', value: '域外异族污染（巡天战皇定性）' },
      { key: 'status', label: '现状', value: '已被巡天令使青沧至尊清剿，九君尽灭' },
    ],
    tags: ['邪道', '云洲', '新兴势力', '域外'],
    relationIds: ['seed-character-duanshanhe', 'seed-faction-tianyimen', 'seed-faction-liujia', 'seed-faction-xuntian', 'seed-character-qingcang', 'seed-location-lianshenya'],
  },
  {
    id: 'seed-faction-liujia',
    name: '柳家',
    type: 'faction',
    icon: '🌳',
    summary: '云洲七世家之一，常被认为末位。实为外洲迁徙逃来的没落贵族。',
    description: '云洲七世家之一，常被人认为是14霸主势力中的倒数第一。直到他们为封锁小柳洲亮出了70+武君、12巅峰武圣——整个云洲沉默了。但没人知道，柳家是从其他洲迁徙逃到云洲的，底蕴早已不复远古。\n\n祖神为柳神——远古武神，已飞升。青沧至尊随口说出柳神名讳时，在场只有柳家老妪柳白听过。',
    fields: [
      { key: 'rank', label: '地位', value: '七世家之一，常被认为末位' },
      { key: 'strength', label: '隐藏实力', value: '70+武君、12巅峰武圣' },
      { key: 'origin', label: '起源', value: '从其他洲迁徙逃到云洲，底蕴不复远古' },
      { key: 'ancestor', label: '祖神', value: '柳神（远古武神，已飞升）' },
      { key: 'enemies', label: '敌对势力', value: '血刀门（常年混战）', linkedEntityId: 'seed-faction-xuedaomen' },
      { key: 'crisis', label: '近期大事', value: '三长老被段山河重创后遭刺杀陨落' },
    ],
    tags: ['世家', '云洲', '没落贵族'],
    relationIds: ['seed-location-yunzhou', 'seed-faction-xuedaomen', 'seed-character-duanshanhe', 'seed-character-qingcang'],
  },
  {
    id: 'seed-faction-xuntian',
    name: '九洲巡天战皇',
    type: 'faction',
    icon: '👑',
    summary: '自称九洲之上的监察组织。实为东洲的霸权。',
    description: '自称九洲之上的监察组织。实则——东洲的霸权。打着"清理域外污染"的旗号，来云洲收割域外技术。战皇为武皇境，已病入膏肓，时日无多。\n\n巡天令使多为武尊境，极少数武帝。来自东洲。表面职责是巡查九洲、清理域外污染，实际行为是收割域外技术、俘虏研究样本、压制其他洲。',
    fields: [
      { key: 'nature', label: '本质', value: '东洲势力，披着"九洲监察"外衣的东洲霸权' },
      { key: 'leader', label: '领袖', value: '巡天战皇（武皇境，已病入膏肓）' },
      { key: 'members', label: '成员', value: '巡天令使（多为武尊，极少数武帝）' },
      { key: 'surface', label: '表面职责', value: '巡查九洲、清理域外污染' },
      { key: 'actual', label: '实际行为', value: '收割域外技术、俘虏研究样本、压制其他洲' },
      { key: 'envoy', label: '巡天令使', value: '青沧至尊（武尊，来云洲清理血刀门）', linkedEntityId: 'seed-character-qingcang' },
    ],
    tags: ['东洲', '霸权', '监察'],
    relationIds: ['seed-character-qingcang', 'seed-faction-xuedaomen', 'seed-realm-wudao'],
  },

  // ========== 人物 ==========
  {
    id: 'seed-character-duanshanhe',
    name: '段山河',
    type: 'character',
    icon: '🩸',
    summary: '血刀门门主，4星武圣。三年从武者攀升至此，可跨境重创9星武圣。',
    description: '原名段刃，战胜9星武圣后改名段山河。云洲本地散修，在炼神崖的梦境中被三位庞大存在赐予传承，受命在天星界建造宗门。三年从武者攀升至4星武圣，战胜柳家三长老后将炼神崖炼化为一柄弯刀，创下绝武神诀，创立血刀门。麾下9位武君效命。\n\n秘技加持下可重创9星武圣——跨境战力。本命弯刀+绝武神诀。已被青沧至尊清剿。',
    fields: [
      { key: 'originName', label: '原名', value: '段刃' },
      { key: 'realm', label: '境界', value: '武圣 4星', linkedEntityId: 'seed-realm-wudao' },
      { key: 'faction', label: '所属势力', value: '血刀门（创始人、门主）', linkedEntityId: 'seed-faction-xuedaomen' },
      { key: 'technique', label: '战技', value: '绝武神诀（自创，云洲广为流传）' },
      { key: 'weapon', label: '本命武器', value: '弯刀（炼化炼神崖而成）', linkedEntityId: 'seed-location-lianshenya' },
      { key: 'combat', label: '战力', value: '4星武圣，秘技可重创9星武圣（跨境战力）' },
      { key: 'experience', label: '经历', value: '三年前炼神崖奇遇→三年攀升→一战成名→炼化炼神崖→创立血刀门' },
      { key: 'mystery', label: '谜团', value: '传承来自三位庞大存在，非九洲武道。其中一位样貌与胖琦一模一样' },
    ],
    tags: ['人物', '血刀门', '武圣', '域外传承'],
    relationIds: ['seed-faction-xuedaomen', 'seed-realm-wudao', 'seed-location-lianshenya', 'seed-faction-liujia', 'seed-character-qingcang'],
  },
  {
    id: 'seed-character-qingcang',
    name: '青沧至尊',
    type: 'character',
    icon: '🧊',
    summary: '青衫武尊。巡天令使，奉命清理云域外污染。云洲五千余年未出武尊。',
    description: '青衫武尊。无声无息出现在十二巅峰武圣身后——群圣竟无一人察觉。奉巡天战皇之命，以巡天令使身份清理域外污染。云洲已五千余年未出武尊。\n\n对柳家态度轻蔑但不含恶意。出手不是为了帮柳家，只是任务目标（清理污染）恰好与柳家目标一致。将血刀门八君全灭后消失，去向不明。',
    fields: [
      { key: 'title', label: '称号', value: '青沧至尊' },
      { key: 'realm', label: '境界', value: '武尊（第十一境）', linkedEntityId: 'seed-realm-wudao' },
      { key: 'faction', label: '所属', value: '九洲巡天战皇', linkedEntityId: 'seed-faction-xuntian' },
      { key: 'role', label: '职位', value: '巡天令使（多为武尊境）' },
      { key: 'mission', label: '任务', value: '清理域外污染——血刀门（已完成，八君全灭）' },
      { key: 'appearance', label: '外貌', value: '青衫，看似寻常，实则深不可测' },
      { key: 'personality', label: '性格', value: '从容、轻蔑、专业。十二巅峰武圣在他眼里不值一提' },
      { key: 'significance', label: '意义', value: '云洲五千余年未出武尊，其现身本身就是震动九洲的大事' },
    ],
    tags: ['人物', '武尊', '巡天战皇', '东洲'],
    relationIds: ['seed-faction-xuntian', 'seed-realm-wudao', 'seed-faction-xuedaomen', 'seed-faction-liujia'],
  },
  {
    id: 'seed-character-sudian',
    name: '苏典',
    type: 'character',
    icon: '🔨',
    summary: '天一门外门弟子，9星武者。擅使火锤，可召唤火锤虚影。',
    description: '天一门的外门弟子，9星武者。擅使火锤，可召唤火锤虚影。苏丰的族兄。务实果断——族弟苏丰惨死，但他没有被仇恨冲昏头脑。\n\n当前状态：与其他数名外门弟子藏身于东方大城另一侧的贫民窟中。曾与萧洛璃一同从梁洵的镇压中逃脱。两人根基扎实，是少数在城内武师围剿下存活的外门弟子。',
    fields: [
      { key: 'realm', label: '境界', value: '武者 9星', linkedEntityId: 'seed-realm-wudao' },
      { key: 'faction', label: '势力', value: '天一门', linkedEntityId: 'seed-faction-tianyimen' },
      { key: 'identity', label: '身份', value: '外门弟子' },
      { key: 'weapon', label: '武器', value: '火锤（地品，仅武者境无法完全催动，最多外显虚影）' },
      { key: 'status', label: '状态', value: '失踪（火锤虚影被击碎，与梁洵一同消失于爆炸中）' },
      { key: 'family', label: '族弟', value: '苏丰（已故，被梁洵击杀）', linkedEntityId: 'seed-character-suofeng' },
      { key: 'ally', label: '同伴', value: '萧洛璃（一同从镇压中逃脱）', linkedEntityId: 'seed-character-xiaoluoli' },
      { key: 'personality', label: '性格', value: '务实、果断，不被仇恨冲昏头脑' },
    ],
    tags: ['人物', '云洲', '天一门', '武者'],
    relationIds: ['seed-faction-tianyimen', 'seed-realm-wudao', 'seed-character-suofeng', 'seed-character-xiaoluoli'],
  },
  {
    id: 'seed-character-suofeng',
    name: '苏丰',
    type: 'character',
    icon: '💀',
    summary: '天一门外门十大武者之一，9星武者。已故——死于东方大城。',
    description: '天一门的外门弟子。外门十大武者之一，实力在五万外门弟子中名列前茅。9星武者。\n\n小世界考核中，降临东方大城。被城中武师击杀。头颅被砍下锁在城门正上方悬吊的铁笼内，身躯被万箭洞穿钉死在主城门一侧的城墙上。此为梁洵的威慑——域外武者，入城者死。',
    fields: [
      { key: 'realm', label: '境界', value: '武者 9星', linkedEntityId: 'seed-realm-wudao' },
      { key: 'faction', label: '势力', value: '天一门', linkedEntityId: 'seed-faction-tianyimen' },
      { key: 'identity', label: '身份', value: '外门十大武者之一' },
      { key: 'status', label: '状态', value: '已故 — 死于东方大城' },
      { key: 'death', label: '死状', value: '头颅悬于城门铁笼，身躯万箭洞穿钉于城墙' },
      { key: 'killer', label: '击杀者', value: '梁洵（东方大城城主，武师）' },
      { key: 'family', label: '族兄', value: '苏典', linkedEntityId: 'seed-character-sudian' },
    ],
    tags: ['人物', '云洲', '天一门', '已故', '武者'],
    relationIds: ['seed-faction-tianyimen', 'seed-realm-wudao', 'seed-character-sudian'],
  },
  {
    id: 'seed-character-xiaoluoli',
    name: '萧洛璃',
    type: 'character',
    icon: '🎵',
    summary: '天一门外门弟子，外号"仙女"。可闪现/瞬移，武器为琵琶。',
    description: '天一门的外门弟子。在外门有"仙女"之名。武器为琵琶（可召唤，疑似音修或特殊流派），能力可闪现/瞬移。\n\n小世界考核中落地后不急于杀戮，慢条斯理唤出琵琶，抱琴闪现离开。东方大城由大梁王朝将军梁洵镇守，数千名降临的武者几乎被就地处决。萧洛璃根基扎实，与苏典成功逃脱。十大外门弟子中唯一的幸存者。\n\n苏典评价萧洛璃"有大背景"——天一门内？还是云洲其他势力？',
    fields: [
      { key: 'alias', label: '外号', value: '仙女' },
      { key: 'realm', label: '境界', value: '外门弟子（具体境界未知）', linkedEntityId: 'seed-realm-wudao' },
      { key: 'faction', label: '势力', value: '天一门', linkedEntityId: 'seed-faction-tianyimen' },
      { key: 'weapon', label: '武器', value: '琵琶（可召唤，疑似音修或特殊流派）' },
      { key: 'ability', label: '能力', value: '可闪现/瞬移' },
      { key: 'status', label: '状态', value: '存活（十大外门弟子中唯一幸存者）' },
      { key: 'ally', label: '同伴', value: '苏典（一同从镇压中逃脱）', linkedEntityId: 'seed-character-sudian' },
      { key: 'mystery', label: '谜团', value: '"有大背景"——天一门内？还是云洲其他势力？' },
    ],
    tags: ['人物', '云洲', '天一门', '音修'],
    relationIds: ['seed-faction-tianyimen', 'seed-realm-wudao', 'seed-character-sudian'],
  },
];
