import type { Entity } from '../types';

// Sample seed data inspired by the omnia world repo (玄幻世界)
export const SEED_ENTITIES: Omit<Entity, 'owner_id' | 'created_at' | 'updated_at'>[] = [
  {
    id: 'seed-realm-qi-refining',
    name: '炼气期',
    type: 'realm',
    icon: '🔮',
    summary: '修仙之路的起点，吸纳天地灵气入体。',
    description: '炼气期是修仙者的第一个境界，分为一到九层。修士在此阶段主要学习如何感应灵气、引气入体、炼化杂质。九层圆满后方可尝试突破筑基。',
    fields: [
      { key: 'order', label: '排序', value: '第一境界' },
      { key: 'requirement', label: '突破条件', value: '炼气九层圆满，需筑基丹辅助' },
      { key: 'ability', label: '能力变化', value: '可施展基础法术，灵力有限' },
      { key: 'lifespan', label: '寿命', value: '约120年' },
    ],
    tags: ['修仙体系', '基础境界'],
    relationIds: ['seed-realm-foundation', 'seed-item-foundation-pill'],
  },
  {
    id: 'seed-realm-foundation',
    name: '筑基期',
    type: 'realm',
    icon: '🔮',
    summary: '奠定道基，真正踏入修仙之门。',
    description: '筑基期分为初期、中期、后期三个小阶。修士在此阶段构建灵力根基，道基品质决定未来成就上限。天品道基可直入金丹，劣品道基终生止步筑基。',
    fields: [
      { key: 'order', label: '排序', value: '第二境界' },
      { key: 'requirement', label: '突破条件', value: '道基稳固，需结丹丹引' },
      { key: 'ability', label: '能力变化', value: '可御剑飞行，法术威力大增' },
      { key: 'lifespan', label: '寿命', value: '约200年' },
    ],
    tags: ['修仙体系'],
    relationIds: ['seed-realm-qi-refining', 'seed-realm-golden-core'],
  },
  {
    id: 'seed-realm-golden-core',
    name: '金丹期',
    type: 'realm',
    icon: '🔮',
    summary: '灵力凝聚成丹，寿元大增。',
    description: '金丹期修士将体内灵力压缩凝聚成一颗金丹，金丹品质分为凡品、良品、上品、极品。金丹品质直接决定元婴期的成就。',
    fields: [
      { key: 'order', label: '排序', value: '第三境界' },
      { key: 'requirement', label: '突破条件', value: '金丹圆满，感悟天地法则' },
      { key: 'ability', label: '能力变化', value: '可施展丹火，神识大幅扩展' },
      { key: 'lifespan', label: '寿命', value: '约500年' },
    ],
    tags: ['修仙体系'],
    relationIds: ['seed-realm-foundation', 'seed-realm-nascent-soul'],
  },
  {
    id: 'seed-realm-nascent-soul',
    name: '元婴期',
    type: 'realm',
    icon: '🔮',
    summary: '金丹化婴，神魂不灭。',
    description: '元婴期修士将金丹孵化为元婴，即使肉身被毁，元婴可遁走夺舍重生。此境界修士已是一方霸主级别存在。',
    fields: [
      { key: 'order', label: '排序', value: '第四境界' },
      { key: 'requirement', label: '突破条件', value: '元婴凝聚，需渡心魔劫' },
      { key: 'ability', label: '能力变化', value: '元婴出窍，夺舍重生' },
      { key: 'lifespan', label: '寿命', value: '约1000年' },
    ],
    tags: ['修仙体系'],
    relationIds: ['seed-realm-golden-core'],
  },
  {
    id: 'seed-faction-qingyun',
    name: '青云宗',
    type: 'faction',
    icon: '🏰',
    summary: '云洲第一大派，传承万年。',
    description: '青云宗坐落于云洲青云山脉，是整个云洲实力最雄厚的修仙宗门。宗门以剑道闻名，门下弟子数万，拥有三位元婴期太上长老。',
    fields: [
      { key: 'origin', label: '起源', value: '万年前青云祖师飞升前所创' },
      { key: 'leader', label: '宗主', value: '云天河', linkedEntityId: 'seed-character-yuntianhe' },
      { key: 'industry', label: '产业', value: '灵矿、丹药贸易、飞剑锻造' },
      { key: 'territory', label: '领地', value: '云洲青云山脉及周边三城' },
      { key: 'ideology', label: '理念', value: '以剑入道，斩妖除魔' },
      { key: 'allies', label: '盟友', value: '天机阁' },
      { key: 'enemies', label: '敌对势力', value: '血魔教' },
    ],
    tags: ['正道', '云洲', '剑修'],
    relationIds: ['seed-character-yuntianhe', 'seed-location-qingyun-mountain'],
  },
  {
    id: 'seed-character-yuntianhe',
    name: '云天河',
    type: 'character',
    icon: '🧙',
    summary: '青云宗当代宗主，金丹巅峰修士。',
    description: '云天河出身云洲云家旁支，幼年被青云宗前宗主收为关门弟子。剑道天赋惊人，三十岁筑基，五十岁结丹，如今百岁有余已达金丹巅峰，随时准备冲击元婴。',
    fields: [
      { key: 'age', label: '年龄', value: '127岁' },
      { key: 'gender', label: '性别', value: '男' },
      { key: 'faction', label: '所属势力', value: '青云宗', linkedEntityId: 'seed-faction-qingyun' },
      { key: 'realm', label: '境界修为', value: '金丹巅峰', linkedEntityId: 'seed-realm-golden-core' },
      { key: 'bloodline', label: '血脉', value: '云家剑脉（旁支）' },
      { key: 'physique', label: '体质', value: '先天剑体' },
      { key: 'talent', label: '天赋', value: '剑心通明' },
      { key: 'technique', label: '功法/神通', value: '青云剑诀、天河剑意' },
      { key: 'family', label: '家族', value: '云洲云家（旁支）' },
      { key: 'friends', label: '朋友', value: '天机阁主·苏墨' },
      { key: 'spouse', label: '道侣', value: '无' },
      { key: 'enemies', label: '仇人', value: '血魔教主' },
      { key: 'equipment', label: '装备', value: '天河剑（上品灵器）' },
      { key: 'treasure', label: '宝物', value: '青云祖师传承玉简' },
      { key: 'background', label: '重大背景故事', value: '幼年家族被灭，被前宗主救起收徒。百年隐忍，一剑斩杀血魔教长老，名震云洲。' },
    ],
    tags: ['正道', '剑修', '青云宗'],
    relationIds: ['seed-faction-qingyun', 'seed-realm-golden-core', 'seed-technique-qingyun-sword'],
  },
  {
    id: 'seed-technique-qingyun-sword',
    name: '青云剑诀',
    type: 'technique',
    icon: '⚡',
    summary: '青云宗镇派剑法，传承万年。',
    description: '青云剑诀共分九重，每一重对应一层剑意。修至大成可化剑意为天河，覆盖方圆百里。传闻第九重需先天剑体方可修炼。',
    fields: [
      { key: 'type', label: '类型', value: '剑道功法' },
      { key: 'rank', label: '品阶', value: '地品上阶' },
      { key: 'origin', label: '来源', value: '青云祖师所创' },
      { key: 'effect', label: '效果', value: '剑意叠加，越战越强' },
      { key: 'prerequisite', label: '修炼条件', value: '需剑灵根，金丹期以上方可修至第五重' },
      { key: 'previousOwner', label: '上一任拥有者', value: '青云祖师' },
    ],
    tags: ['剑道', '青云宗', '镇派功法'],
    relationIds: ['seed-faction-qingyun', 'seed-character-yuntianhe'],
  },
  {
    id: 'seed-location-qingyun-mountain',
    name: '青云山脉',
    type: 'location',
    icon: '🗺️',
    summary: '云洲第一灵脉所在地，青云宗驻地。',
    description: '青云山脉横贯云洲中部，山中灵气浓郁，有七座主峰呈北斗排列。青云宗宗门建在北斗第七峰——摇光峰上。',
    fields: [
      { key: 'region', label: '所属区域', value: '云洲中部' },
      { key: 'ruler', label: '统治者', value: '青云宗', linkedEntityId: 'seed-faction-qingyun' },
      { key: 'climate', label: '气候', value: '四季如春，灵气充沛' },
      { key: 'resources', label: '资源', value: '灵石矿脉、天材地宝' },
      { key: 'danger', label: '危险等级', value: '外围安全，深处有妖兽' },
      { key: 'history', label: '历史', value: '万年前青云祖师在此悟道飞升' },
    ],
    tags: ['云洲', '灵脉'],
    relationIds: ['seed-faction-qingyun'],
  },
  {
    id: 'seed-item-foundation-pill',
    name: '筑基丹',
    type: 'item',
    icon: '💊',
    summary: '炼气修士突破筑基的关键丹药。',
    description: '筑基丹由三十六种灵药炼制，可帮助炼气九层修士稳固道基，提高筑基成功率。品质分为凡品、良品、上品，上品筑基丹可使道基品质提升一个小阶。',
    fields: [
      { key: 'type', label: '类型', value: '突破丹药' },
      { key: 'rank', label: '品阶', value: '黄品上阶' },
      { key: 'effect', label: '效果', value: '辅助筑基，提升道基品质' },
      { key: 'origin', label: '来源', value: '丹道宗师炼制' },
      { key: 'owner', label: '持有者', value: '各大宗门均有储备' },
    ],
    tags: ['丹药', '突破'],
    relationIds: ['seed-realm-qi-refining', 'seed-realm-foundation'],
  },
];
